name: Django CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r myapi/requirements.txt

    - name: Run tests
      run: |
        cd myapi
        python manage.py test

    - name: Trigger API with Authentication
      run: |
        curl -X POST http://127.0.0.1:8000/books/ \
          -H "Content-Type: application/json" \
          -H "Authorization: Token ${{ secrets.API_TOKEN }}" \
          -d '{"title": "New Book", "author": "Author Name"}'
